const supa = {
  name: "Supa",
  colors: {
    keyword: "#bda4ff",
    type: "#3ecf8e",
    property: "#d0d0c8",
    string: "#ffcda1"
  },
}

const zandromeda = {
  name: "Zandromeda",
  colors: {
    keyword: "#10a793",
    type: "#08e7c5",
    property: "#fee56c",
    string: "#f29c14"
  },
}

function schema({ name, colors, styles }) {
  return `
    {
      "name": "${name}",
      "colors": {
        "foreground": "#f7f7f8",
        "focusBorder": "#171717",
        "selection.background": "#1f1f1f",
        "scrollbar.shadow": "#00000000",
        "activityBar.foreground": "#f7f7f8",
        "activityBar.background": "#202020",
        "activityBar.inactiveForeground": "#ffffff66",
        "activityBarBadge.foreground": "#ffffff",
        "activityBarBadge.background": "${colors.type}",
        "activityBar.border": "#2b2f38",
        "activityBar.activeBackground": "#fbfbfb0a",
        "sideBar.background": "#202020",
        "sideBar.foreground": "#aca8aeff",
        "sideBar.border": "#1a1a1a",
        "sideBarSectionHeader.background": "#00000000",
        "sideBarSectionHeader.foreground": "#cccccc",
        "sideBarSectionHeader.border": "#cccccc33",
        "sideBarTitle.foreground": "#bbbbbb",
        "tree.indentGuidesStroke": "#585858",
        "list.inactiveSelectionBackground": "#171717",
        "list.inactiveSelectionForeground": "#cccccc",
        "list.hoverBackground": "#171717",
        "list.hoverForeground": "#cccccc",
        "list.activeSelectionBackground": "#171717",
        "list.activeSelectionForeground": "#ffffff",
        "list.dropBackground": "#383b3d",
        "list.highlightForeground": "${colors.type}",
        "list.focusBackground": "#171717",
        "list.focusForeground": "#f7f7f8",
        "listFilterWidget.background": "${colors.type}",
        "listFilterWidget.outline": "#00000000",
        "listFilterWidget.noMatchesOutline": "#12231f",
        "statusBar.noFolderBorder": "#2b2f38",
        "statusBar.foreground": "#f7f7f8",
        "statusBar.background": "#202020",
        "statusBar.border": "#2b2f38",
        "statusBar.focusBorder": "#2b2f38",
        "statusBar.debuggingBorder": "#252526",
        "statusBar.debuggingBackground": "#2b2f38",
        "statusBar.debuggingForeground": "#ffffff",
        "statusBar.noFolderBackground": "#262933",
        "statusBar.noFolderForeground": "#f7f7f8",
        "statusBarItem.errorBackground": "#ad0540",
        "statusBarItem.hoverBackground": "#ffffff1f",
        "statusBarItem.remoteBackground": "#21242e",
        "statusBarItem.remoteForeground": "#ffffff",
        "titleBar.activeBackground": "#202020",
        "titleBar.activeForeground": "#aca8aeff",
        "titleBar.inactiveBackground": "#202020",
        "titleBar.inactiveForeground": "#aca8aeff",
        "titleBar.border": "#1a1a1a",
        "menubar.selectionForeground": "#f7f7f8",
        "menubar.selectionBackground": "#1f1f1f",
        "menu.foreground": "#f7f7f8",
        "menu.background": "#202020",
        "menu.selectionForeground": "#f7f7f8",
        "menu.selectionBackground": "#1f1f1f",
        "menu.selectionBorder": "#00000000",
        "menu.separatorBackground": "#2b2f38",
        "menu.border": "#2b2f38",
        "button.background": "#202020",
        "button.foreground": "#ffffff",
        "button.hoverBackground": "#333333",
        "button.secondaryForeground": "#ffffff",
        "button.secondaryBackground": "#252832",
        "button.secondaryHoverBackground": "#2a2e3b",
        "input.background": "#171717",
        "input.border": "#1a1f1f",
        "input.foreground": "#f7f7f8",
        "inputOption.activeBackground": "#31929266",
        "inputOption.activeBorder": "#007acc00",
        "inputOption.activeForeground": "#ffffff",
        "input.placeholderForeground": "#a6a6a6",
        "textLink.foreground": "${colors.type}",
        "textLink.activeForeground": "${colors.type}",
        "editor.background": "#171717",
        "editor.foreground": "#f7f7f8",
        "editorLineNumber.foreground": "#565960",
        "editorCursor.foreground": "#5de4c7",
        "editorCursor.background": "#050505",
        "editor.selectionBackground": "#1f1f1f",
        "editor.inactiveSelectionBackground": "#1f1f1f",
        "editorWhitespace.foreground": "#e3e4e229",
        "editor.selectionHighlightBackground": "#1f1f1f",
        "editor.selectionHighlightBorder": "${colors.type}",
        "editor.findMatchBackground": "#11a79366",
        "editor.findMatchBorder": "${colors.type}",
        "editor.findMatchHighlightBackground": "#333333",
        "editor.findMatchHighlightBorder": "#ffffff00",
        "editor.findRangeHighlightBackground": "#3a3d4166",
        "editor.findRangeHighlightBorder": "#ffffff00",
        "editor.rangeHighlightBackground": "#ffffff0b",
        "editor.rangeHighlightBorder": "#ffffff00",
        "editor.hoverHighlightBackground": "#1f1f1f",
        "editor.wordHighlightStrongBackground": "${colors.type}",
        "editor.wordHighlightBackground": "#575757b8",
        "editor.lineHighlightBackground": "#1f1f1f",
        "editor.lineHighlightBorder": "#1a1a1a",
        "editorLineNumber.activeForeground": "#f8f8f9",
        "editorLink.activeForeground": "${colors.type}",
        "editorIndentGuide.background": "#1f1f1f",
        "editorIndentGuide.activeBackground": "#333333",
        "editorRuler.foreground": "#5a5a5a",
        "editorBracketMatch.background": "#0064001a",
        "editorBracketMatch.border": "#888888",
        "editor.foldBackground": "#264f784d",
        "editorOverviewRuler.background": "#25252500",
        "editorOverviewRuler.border": "#7f7f7f4d",
        "editorError.foreground": "#f82871",
        "editorWarning.foreground": "#fa973a",
        "editorInfo.foreground": "${colors.type}",
        "editorGutter.background": "#171717",
        "editorGutter.modifiedBackground": "#5c5014",
        "editorGutter.addedBackground": "#12231f",
        "editorGutter.deletedBackground": "#54051b",
        "editorGutter.foldingControlForeground": "#c5c5c5",
        "editorCodeLens.foreground": "#999999",
        "editorGroup.border": "#2b2f38",
        "diffEditor.insertedTextBackground": "#9bb95533",
        "diffEditor.removedTextBackground": "#ff000033",
        "diffEditor.border": "#444444",
        "sash.hoverBorder": "#1a1a1a",
        "panel.background": "#202020",
        "panel.border": "#1a1a1a",
        "panelTitle.activeBorder": "#e7e7e7",
        "panelTitle.activeForeground": "#e7e7e7",
        "panelTitle.inactiveForeground": "#e7e7e799",
        "panelSection.border": "#2b2f38",
        "badge.background": "#4d4d4d",
        "badge.foreground": "#ffffff",
        "terminal.foreground": "#cccccc",
        "terminal.background": "#202020",
        "terminal.selectionBackground": "#ffffff40",
        "terminalCursor.background": "#050505",
        "terminalCursor.foreground": "#5de4c7",
        "terminal.border": "#2b2f38",
        "terminal.ansiBlack": "#000000",
        "terminal.ansiBlue": "#2472c8",
        "terminal.ansiBrightBlack": "#666666",
        "terminal.ansiBrightBlue": "#3b8eea",
        "terminal.ansiBrightCyan": "#29b8db",
        "terminal.ansiBrightGreen": "#23d18b",
        "terminal.ansiBrightMagenta": "#d670d6",
        "terminal.ansiBrightRed": "#f14c4c",
        "terminal.ansiBrightWhite": "#e5e5e5",
        "terminal.ansiBrightYellow": "#f5f543",
        "terminal.ansiCyan": "#11a8cd",
        "terminal.ansiGreen": "#0dbc79",
        "terminal.ansiMagenta": "#bc3fbc",
        "terminal.ansiRed": "#cd3131",
        "terminal.ansiWhite": "#e5e5e5",
        "terminal.ansiYellow": "#e5e510",
        "breadcrumb.background": "#1e2025ff",
        "breadcrumb.foreground": "#cccccccc",
        "breadcrumb.focusForeground": "#e0e0e0",
        "editorGroupHeader.border": "#1a1a1a",
        "editorGroupHeader.tabsBorder": "#00000000",
        "editorGroupHeader.tabsBackground": "#202020",
        "tab.unfocusedActiveBorder": "#252526",
        "tab.activeForeground": "#f7f7f8ff",
        "tab.inactiveForeground": "#aca8aeff",
        "tab.selectedForeground": "#f7f7f8ff",
        "tab.border": "#1a1a1a",
        "tab.inactiveModifiedBorder": "#252526",
        "tab.activeBackground": "#1e2025ff",
        "tab.activeBorder": "#1e2025",
        "tab.activeBorderTop": "#00000000",
        "tab.inactiveBackground": "#171717",
        "scrollbarSlider.background": "#79797966",
        "scrollbarSlider.hoverBackground": "#646464b3",
        "scrollbarSlider.activeBackground": "#bfbfbf66",
        "progressBar.background": "#262933",
        "widget.shadow": "#0000002f",
        "editorSuggestWidget.background": "#202020",
        "editorSuggestWidget.border": "#2b2f38",
        "editorSuggestWidget.foreground": "#f7f7f8",
        "editorSuggestWidget.highlightForeground": "${colors.type}",
        "editorSuggestWidget.selectedBackground": "#1f1f1f",
        "editorWidget.foreground": "#cccccc",
        "editorWidget.background": "#202020",
        "editorWidget.resizeBorder": "#5F5F5F",
        "editorHoverWidget.statusBarBackground": "#1f1f1f",
        "pickerGroup.border": "#3f3f46",
        "pickerGroup.foreground": "#3794ff",
        "debugToolBar.background": "#202020",
        "debugToolBar.border": "#252526",
        "notifications.foreground": "#f7f7f8ff",
        "notifications.background": "#202020",
        "notificationToast.border": "#474747",
        "notificationsErrorIcon.foreground": "#f48771",
        "notificationsWarningIcon.foreground": "#cca700",
        "notificationsInfoIcon.foreground": "#75beff",
        "notificationCenter.border": "#1a1a1a",
        "notificationCenterHeader.foreground": "#f48771",
        "notificationCenterHeader.background": "#202020",
        "notifications.border": "#2b2f38",
        "gitDecoration.addedResourceForeground": "#81b88b",
        "gitDecoration.conflictingResourceForeground": "#6c6cc4",
        "gitDecoration.deletedResourceForeground": "#c74e39",
        "gitDecoration.ignoredResourceForeground": "#8c8c8c",
        "gitDecoration.modifiedResourceForeground": "#e2c08d",
        "gitDecoration.stageDeletedResourceForeground": "#c74e39",
        "gitDecoration.stageModifiedResourceForeground": "#e2c08d",
        "gitDecoration.submoduleResourceForeground": "#8db9e2",
        "gitDecoration.untrackedResourceForeground": "#73c991",
        "editorMarkerNavigation.background": "#202020",
        "editorMarkerNavigationError.background": "#f82871",
        "editorMarkerNavigationWarning.background": "#fa973a",
        "editorMarkerNavigationInfo.background": "${colors.type}",
        "merge.currentHeaderBackground": "#367366",
        "merge.currentContentBackground": "#27403B",
        "merge.incomingHeaderBackground": "#395F8F",
        "merge.incomingContentBackground": "#28384B",
        "merge.commonHeaderBackground": "#383838",
        "merge.commonContentBackground": "#282828",
        "editorHoverWidget.foreground": "#f7f7f8",
        "editorHoverWidget.background": "#202020",
        "editorHoverWidget.border": "#2b2f38",
        "peekView.border": "#2b2f38",
        "peekViewEditor.background": "#202020",
        "peekViewEditorGutter.background": "#202020",
        "peekViewEditor.matchHighlightBackground": "#333",
        "peekViewEditor.matchHighlightBorder": "#555",
        "peekViewResult.background": "#202020",
        "peekViewResult.fileForeground": "#ffffff",
        "peekViewResult.lineForeground": "#bbbbbb",
        "peekViewResult.matchHighlightBackground": "#333",
        "peekViewResult.selectionBackground": "#1f1f1f",
        "peekViewResult.selectionForeground": "#ffffff",
        "peekViewTitle.background": "#202020",
        "peekViewTitleDescription.foreground": "#f7f7f8",
        "peekViewTitleLabel.foreground": "#f7f7f8",
        "icon.foreground": "#f7f7f8",
        "checkbox.background": "#202020",
        "checkbox.foreground": "#f7f7f8",
        "checkbox.border": "#2b2f38",
        "dropdown.background": "#202020",
        "dropdown.foreground": "#f7f7f8",
        "dropdown.border": "#2b2f38",
        "quickInput.background": "#202020",
        "minimapGutter.addedBackground": "#12231f",
        "minimapGutter.modifiedBackground": "#5c5014",
        "minimapGutter.deletedBackground": "#54051b",
        "minimap.findMatchHighlight": "#11a79366",
        "minimap.selectionHighlight": "#1f1f1f",
        "minimap.errorHighlight": "#f82871",
        "minimap.warningHighlight": "#fa973a",
        "minimap.background": "#1e2025",
        "sideBar.dropBackground": "#383b3d",
        "editorGroup.emptyBackground": "#1e2025",
        "statusBarItem.activeBackground": "#FFFFFF25",
        "settings.headerForeground": "#f7f7f8",
        "settings.focusedRowBackground": "#ffffff07",
        "walkThrough.embeddedEditorBackground": "#00000050",
        "breadcrumb.activeSelectionForeground": "#e0e0e0",
        "editorGutter.commentRangeForeground": "#c5c5c5",
        "debugExceptionWidget.background": "#202020",
        "debugExceptionWidget.border": "#2b2f38"
      },
      "semanticHighlighting": true,
      "semanticTokenColors": {
        "variable": "#ffffff",
        "variable.defaultLibrary": "${colors.keyword}",
        "parameter": "#ffffff",
        "builtinAttribute": "${colors.keyword}",
        "builtinType": "${colors.keyword}",
        "decorator": "${colors.keyword}",
        "keyword": "${colors.keyword}",
        "keyword.crateRoot": "#ffffff",
        "macro": "${colors.keyword}",
        "field": "#ffffff",
        "const": "${colors.type}",
        "constant": "${colors.type}",
        "type": "${colors.type}",
        "struct": "${colors.type}",
        "class": "${colors.type}",
        "interface": "${colors.type}",
        "enum": "${colors.type}",
        "enumMember": "${colors.property}",
        "namespace": "${colors.type}",
        "namespace.crateRoot": "#ffffff",
        "number": "${colors.string}",
        "string": "${colors.string}",
        "operator": "${colors.string}",
        "method": "${colors.property}",
        "function": "${colors.property}",
        "property": "${colors.property}",
        "comment": "#afabb1ff"
      },
      "tokenColors": [
        {
          "name": "attribute",
          "scope": "entity.other.attribute-name",
          "settings": {
            "foreground": "${colors.property}"
          }
        },
        {
          "name": "property",
          "scope": "variable.other.property, support.type.property-name",
          "settings": {
            "foreground": "${colors.property}"
          }
        },
        {
          "name": "type",
          "scope": "entity.name.type, variable.other.constant",
          "settings": {
            "foreground": "${colors.type}"
          }
        },
        {
          "name": "boolean",
          "scope": "",
          "settings": {
            "foreground": "#f7f7f8"
          }
        },
        {
          "name": "variable",
          "scope": "entity.name.label, variable.other.readwrite",
          "settings": {
            "foreground": "#f7f7f8"
          }
        },
        {
          "name": "keyword",
          "scope": "support.type,support.function.misc,support.type.property-name.css, entity.name.tag, keyword.operator.new, storage.type, keyword.control, keyword.operator.expression, support.type.primitive, constant.language, storage.modifier",
          "settings": {
            "foreground": "${colors.keyword}"
          }
        },
        {
          "name": "function",
          "scope": "",
          "settings": {
            "foreground": "#f7f7f8"
          }
        },
        {
          "name": "number",
          "scope": "constant.numeric",
          "settings": {
            "foreground": "${colors.string}"
          }
        },
        {
          "name": "operator",
          "scope": "keyword.other.important.css, support.constant.vendored.property-value,support.constant.property-value,keyword.operator, storage.type.function.arrow",
          "settings": {
            "foreground": "${colors.string}"
          }
        },
        {
          "name": "punctuation",
          "scope": "punctuation.semi, punctuation.definition, punctuation.terminator, punctuation.separator",
          "settings": {
            "foreground": "#ffffff"
          }
        },
        {
          "name": "punctuation.bracket",
          "scope": "meta.brace, punctuation.brackets",
          "settings": {
            "foreground": "#ffffff"
          }
        },
        {
          "name": "punctuation.delimiter",
          "scope": "punctuation.definition.template-expression, punctuation.definition.string.template",
          "settings": {
            "foreground": "${colors.string}"
          }
        },
        {
          "name": "string",
          "scope": "string.quoted, string.template, punctuation.definition.string",
          "settings": {
            "foreground": "${colors.string}"
          }
        },
        {
          "name": "comment",
          "scope": "comment.line, punctuation.definition.comment, comment.block",
          "settings": {
            "foreground": "#afabb1ff"
          }
        }
      ]
    }
  `
}

module.exports.schema = schema
module.exports.supa = supa
module.exports.zandromeda = zandromeda